### ISSUE TITLE
iOS SDK Crash - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ArjunSomanadhan** [Adobe-Marketing-Cloud/acp-sdks#440] opened 2020-09-23 05:30 UTC
**Problem**

We're seeing a crash in the iOS SDK that seems like it could be related to accessing Adobe marketing SDK

**Environment**

iOS Version: 10.3.3 (14G60), 10.3.4 (14G61)
Adobe SDK Version:
ACPCore 2.6.0
ACPAnalytics 2.2.3
ACPTarget 2.1.6
ACPUserProfile 2.1.0
Steps to reproduce: Unknown. Actively trying to reproduce.

**SDK Integration**

We've integrated with the Adobe SDK using cocoapods. Here is a rough code sample of how we initialize and use the SDK.

        ACPCore.setLogLevel(.debug)
        ACPCore.configure(withAppId: ID)
        ACPTarget.registerExtension()
        ACPAnalytics.registerExtension()
        ACPIdentity.registerExtension()
        ACPLifecycle.registerExtension()
        ACPSignal.registerExtension()
        ACPUserProfile.registerExtension()
        ACPCore.start({
        ACPCore.lifecycleStart(nil)
        })

**Crash log:**

Crashed: Thread #1
EXC_BAD_ACCESS 0x0000000019b5b9ca
keyboard_arrow_up
arrow_right 0
FPL
AdobeMarketingMobile::ZipCompressedFile::LoadLocalFileHeader() + 4390138
1
FPL
AdobeMarketingMobile::ZipCompressedFile::LoadLocalFileHeader() + 4390123
2
FPL
AdobeMarketingMobile::ZipCompressedFile::ZipCompressedFile(std::__1::shared_ptr<AdobeMarketingMobile::FileHandlerInterface> const&, long long) + 4387063
3
FPL
AdobeMarketingMobile::ZipFile::LoadFileHeaders() + 4406527
4
FPL
AdobeMarketingMobile::ZipFile::ZipFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4407093
5
FPL
(anonymous namespace)::NativeCompressedFileService::Extract(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, AdobeMarketingMobile::CompressedFileType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4371205
6
FPL
std::__1::__function::__func<AdobeMarketingMobile::ZipBundleHandler::ProcessDownloadedBundle(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0, std::__1::allocator<AdobeMarketingMobile::ZipBundleHandler::ProcessDownloadedBundle(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>, void ()>::operator()() + 5126611
7
FPL
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4922739
8
FPL
AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 4922521
9
FPL
AdobeMarketingMobile::ZipBundleHandler::ProcessDownloadedBundle(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 5126107
10
FPL
AdobeMarketingMobile::RulesDownloader::ProcessBundle(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 5098011
11
FPL
AdobeMarketingMobile::RulesDownloader::OnDownloadComplete(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 5097615
12
FPL
AdobeMarketingMobile::RulesDownloader::StartDownload(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 5097173
13
FPL
std::__1::__function::__func<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10::operator()() const::'lambda'(), std::__1::allocator<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10::operator()() const::'lambda'()>, void ()>::operator()() + 4720993
14
FPL
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4922739
15
FPL
std::__1::__function::__func<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10, std::__1::allocator<AdobeMarketingMobile::Configuration::DownloadRules(std::__1::shared_ptr<AdobeMarketingMobile::EventData> const&)::$_10>, void ()>::operator()() + 4720193
16
FPL
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4922739
17
FPL
AdobeMarketingMobile::(anonymous namespace)::ProxyTaskExecutor::ParentTask(std::__1::shared_ptr<AdobeMarketingMobile::(anonymous namespace)::ProxyTaskExecutorData> const&) + 4906791
18
FPL
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4922739
19
FPL
AdobeMarketingMobile::(anonymous namespace)::ProxyTaskExecutor::ParentTask(std::__1::shared_ptr<AdobeMarketingMobile::(anonymous namespace)::ProxyTaskExecutorData> const&) + 4906791
20
FPL
std::__1::__function::__func<AdobeMarketingMobile::(anonymous namespace)::NativeTaskExecutor::AddTaskImpl(std::__1::function<void ()>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, AdobeMarketingMobile::SdkError&)>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0, std::__1::allocator<AdobeMarketingMobile::(anonymous namespace)::NativeTaskExecutor::AddTaskImpl(std::__1::function<void ()>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, AdobeMarketingMobile::SdkError&)>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>, void ()>::operator()() + 4298971
21
FPL
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4922739
22
FPL
std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2::operator()() const::'lambda0'(), std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2::operator()() const::'lambda0'()>, void ()>::operator()() + 4935555
23
FPL
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4922739
24
FPL
AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 4922521
25
FPL
std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 4934319
26
FPL
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4922739
27
FPL
AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 4922521
28
FPL
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 4933287
29
libsystem_pthread.dylib
_pthread_body + 216
31 arrow_drop_down
libsystem_pthread.dylib
thread_start + 8

**Comment by cacheung** [comment] 2020-09-23 17:46
Hi,
   It seems like the crash happened with downloading the rule zip.  We have a rule crash fix in a newer build. 
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/mobile-core-release-notes#aug-10-2020.
Please update to the latest ACPCore and see can still reproduce the crash.

Best Regards,
Calise Cheung
Mobile Engineer

**Comment by cacheung** [comment] 2020-09-23 18:55
Hi,
We found out this crash isn't the same as the one we fixed earlier.  How often are you seeing the crash?
You could contact [customer care](https://helpx.adobe.com/contact/enterprise-support.ec.html) and open a ticket with any reproducible info you have and we can take a look of the app id.

Best Regards,
Calise Cheung
Mobile Engineer

**Comment by Laura-Lo** [comment] 2020-10-14 16:05
Hi,
We are also seeing this crash in our app. It seems to be happening only for iOS 10. Do you have any updates about this issue?

Best regards,
Laura López

**Comment by cacheung** [comment] 2020-10-14 16:19
Please contact [customer care](https://helpx.adobe.com/contact/enterprise-support.ec.html) and open a ticket with any reproducible info you have including app id and we can take a look of the logs.

Best Regards,
Calise Cheung
Mobile Engineer

**Comment by mhk4g** [comment] 2020-11-04 19:53
Seeing this on our end as well, specifically on iOS 10.3 devices. The exception subtype in our case is `EXC_ARM_DA_ALIGN` which indicates a memory alignment error. Occurring in the `ZipCompressedFile::LoadLocalFileHeader()` function for us as well.

**Comment by sbenedicadb** [comment] 2020-11-18 22:47
Hey all,

[ACPCore 2.8.1](https://github.com/Adobe-Marketing-Cloud/acp-sdks/releases/tag/v2.8.1-ACPCore) was released today which contains a fix for this issue.  Thanks.

-steveb

**Closed** 2020-11-18 22:47 UTC
