### ISSUE TITLE
iOS - EXC_BAD_ACCESS KERN_INVALID_ADDRESS 

### ISSUE THREAD

**Issue by linknaruto77** [Adobe-Marketing-Cloud/acp-sdks#380] opened 2020-05-26 09:31 UTC
Hi all,

I'm having a crash in my app while using ACP SDK.

**Environment**

ACPCore - 2.3.4
ACPAnalytics - 2.2.1
ACPPlaces - 1.2.0
ACPAudience - 2.0.1
ACPTarget - 2.1.4
ACPMobileServices - 1.0.4
ACPUserProfile - 2.0.1

**Crash Log**

```Crashed: Thread
0  Tracker                        0x105573578 std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase>, std::__1::allocator<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase> > > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase>, std::__1::allocator<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase>, std::__1::allocator<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase> > > > > >::erase(std::__1::__tree_const_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase>, std::__1::allocator<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase> > > >, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase>, std::__1::allocator<std::__1::shared_ptr<AdobeMarketingMobile::ModuleEventListenerBase> > > >, void*>*, long>) + 9172
1  Tracker                        0x105573af4 std::__1::__function::__func<AdobeMarketingMobile::EventHubInner::RegisterOneTimeListener(unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, std::__1::function<void (std::__1::shared_ptr<AdobeMarketingMobile::Event> const&)> const&, std::__1::function<void (AdobeMarketingMobile::SdkError const&)> const&)::$_10, std::__1::allocator<AdobeMarketingMobile::EventHubInner::RegisterOneTimeListener(unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, std::__1::function<void (std::__1::shared_ptr<AdobeMarketingMobile::Event> const&)> const&, std::__1::function<void (AdobeMarketingMobile::SdkError const&)> const&)::$_10>, void ()>::operator()() + 10576
2  Tracker                        0x105588874 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 32
3  Tracker                        0x1055887c8 AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 60
4  Tracker                        0x10558f1e0 std::__1::__function::__func<AdobeMarketingMobile::Timer::StartTimerThread()::$_0, std::__1::allocator<AdobeMarketingMobile::Timer::StartTimerThread()::$_0>, void ()>::operator()() + 1608
5  Tracker                        0x105588874 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 32
6  Tracker                        0x10558c1e0 std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2::operator()() const::'lambda0'(), std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2::operator()() const::'lambda0'()>, void ()>::operator()() + 3876
7  Tracker                        0x105588874 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 32
8  Tracker                        0x1055887c8 AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 60
9  Tracker                        0x10558bbbc std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 2304
10 Tracker                        0x105588874 AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 32
11 Tracker                        0x1055887c8 AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 60
12 Tracker                        0x10558b73c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 1152
13 libsystem_pthread.dylib        0x1a36c3d98 _pthread_start + 156
14 libsystem_pthread.dylib        0x1a36c774c thread_start + 8
```

Here's how i initialised it:

``` 
let appId = "My app ID"
ACPCore.configure(withAppId: appId)
ACPAnalytics.registerExtension()
ACPIdentity.registerExtension()
ACPLifecycle.registerExtension()
ACPPlaces.registerExtension()
ACPAudience.registerExtension()
ACPTarget.registerExtension()
ACPMobileServices.registerExtension()
ACPAnalytics.registerExtension()
ACPUserProfile.registerExtension()
ACPIdentity.registerExtension()
ACPLifecycle.registerExtension()
ACPSignal.registerExtension()
ACPCore.start {
    ACPCore.lifecycleStart(nil)
    ACPIdentity.getExperienceCloudId { ... }
}
```

Any help would be appreciated.

**Comment by rymorale** [comment] 2020-05-26 17:43
Thanks for the information @linknaruto77 . We will investigate the issue further and will update this ticket if we have any new information.

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by rymorale** [comment] 2020-05-26 18:17
Hi @linknaruto77, could you update to the latest versions of the ACPSDK cocoapods? Also, if the issue is still occurring after updating, could we get a full crash log?

Thanks,
Ryan

**Comment by jdhuggins** [comment] 2020-06-03 13:29
I am seeing the same stack trace appearing in logs since updating to XCode 11.5. Which Pod is this coming from?

**Comment by rymorale** [comment] 2020-06-03 15:20
Hi @jdhuggins,

Which versions of the ACP SDK pods are you using? Could we also get a full crash log if possible?

Thanks,
Ryan

**Comment by jdhuggins** [comment] 2020-06-03 18:38
Updating to the latest version of the pods seems to have resolved the issue.

**Comment by rymorale** [comment] 2020-06-03 18:40
Thanks for the update @jdhuggins. @linknaruto77, I'm closing this issue. Please re-open the issue if it is still occurring when using the latest ACP SDK cocoapods.

**Closed by rymorale** 2020-06-03 18:40 UTC
