### ISSUE TITLE
"No such module ACPCore"

### ISSUE THREAD

**Issue by funcJeff** [Adobe-Marketing-Cloud/acp-sdks#525] opened 2021-02-13 20:03 UTC
I cannot get the SDK to import its modules. I have tried CocoaPods and manual. I have used libraries in projects successfully before, but this one has me stumped.

As a counter example, I tried the manual install of Google's Firebase. I downloaded the tar.gz file. In Xcode, I selected my target, and chose General > 'Frameworks, Libraries, and Embedded Content'. I pointed it as the FirebaseCore.xcframework file. Seconds later, I can type `import FirebaseCore` in a file and it worked.

Please call up Google Firebase team and ask them how to create an easy-to-integrate library. Or look at what they've done and imitate it.

I have spent 2 days experimenting with manual installs and bridging headers and CocoPod installations. They all result in the same thing. `No such module ACPCore` build error when I type `import ACPCore` in a file.

Here is the link to the Google Firebase libs that work like a charm: https://firebase.google.com/download/ios

I see some diffs in their Info.plist compared to yours, but I'm not knowledgable enough to figure out the key differences.

**Comment by nporter-adbe** [comment] 2021-02-14 01:07
Hi, @funcJeff I'm sorry to hear that you are having trouble installing our SDKs within your application. I can assure you that we do not need to call up the Firebase team for tips on creating a library, our SDKs have been installed many times without issue.

It's difficult to diagnose the exact issue you are running into without a sample project that demonstrates the problem or steps to reproduce the issue, so I'll do my best.

Regarding the issue seeing when pod installing: I'd make sure you are opening the workspace and not the Xcode project.
For the manual install method: I'd like to point out that you do not need to `import ACPCore` when the SDK is imported via a bridging header; therefore, it would be expected for `import ACPCore` to fail. However, you should have access to all the SDK APIs where needed since it is already imported in the bridging header.

More info can be found here: https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift

I've quickly put together two separate applications that install the SDK via Cocoapods and manually. I did not need to do anything out of the ordinary to get these projects to build successfully. I hope you find them useful.

Pod repo: https://github.com/nporter-adbe/pod-demo-acp
Manual install repo: https://github.com/nporter-adbe/manual-install-acp

If are still unable to install the SDK after referencing the repos linked, please share steps to reproduce the issue or share a sample app that demonstrates the issue and we'll be sure to get everything sorted out.

**Comment by funcJeff** [comment] 2021-02-14 01:50
Porter wrote:
> Manual install repo: https://github.com/nporter-adbe/manual-install-acp

Thank you. I'll be looking closely at this.

> I can assure you that we do not need to call up the Firebase team for tips on creating a library

I beg of you to do their manual install and experience it. It's 1) download, 2) add to target, 3) `import` works.

Other frameworks have the same behavior. This one does not do that. Surely, you can see there is room for improvement?

**Comment by funcJeff** [comment] 2021-02-14 02:06
@nporter-adbe 

LOL! You literally sent me a project that has the same problem I have. It should build when I `import ACPCore`. For your test to be good you actually have to attempt to use the library in the app.

<img width="750" alt="Screen Shot 2021-02-13 at 7 59 48 PM copy" src="https://user-images.githubusercontent.com/2448801/107866454-cf4ab080-6e36-11eb-9210-71b92646a537.png">

**Comment by nporter-adbe** [comment] 2021-02-14 02:13
@funcJeff Sure, there is always room for improvement. We can investigate including a module map in the download to support the `import ACPCore` style imports with the manual install. However, the SDK still functions as you'd expect when it's imported via the bridging header.

> For your test to be good you actually have to attempt to use the library in the app.

Please see line 19 in your screenshot. The library is being used in the app. The point is that when you import the library from the bridging header, you do not need to import it anywhere else. The `import` statement you are attempting to use isn't compiling due to no module map existing for our frameworks.

As mentioned above, we'll investigate including a module map to ensure consistent workflows across the install methods. However, in the meantime, the SDK still functions and can be used in both the manual and the pod install methods.

**Comment by funcJeff** [comment] 2021-02-14 23:14
Looking at [module map syntax](https://clang.llvm.org/docs/Modules.html#module-declaration), it looks like it is going to be a beast to figure it out for ACP. But my choices are figure it out myself or use the Obj-C bridging header kludge.

Thanks. Got it.

**Comment by nporter-adbe** [comment] 2021-02-14 23:56
@funcJeff You've also got the option of Cocoapods which is the preferred install method. In your original post you detail issues with installing via Cocoapods, are you still experiencing issues?

**Comment by funcJeff** [comment] 2021-02-15 00:04
Oh, yeah. Sorry. Problem solved.

Just not the way I want. My experiments with Cocoapods were done on personal equipment and not company equipment. I did it to see what I was missing in my manual installation. I am unable to use Cocoapods on company equipment/network.

I will be going forward with manual install + Obj-C bridging header. When I have time, I’ll come back and learn module map syntax so I can use ‘import’.

**Comment by funcJeff** [comment] 2021-02-15 01:48
@nporter-adbe Actually, I was wrong. Now I've got a new problem.

We use Adobe SDK by wrapping in a Swift framework. So now I am getting a new build error with the bridging header.

```
error: using bridging headers with framework targets is unsupported
Command CompileSwiftSources failed with a nonzero exit code
```

So it looks like I will have to use a module map. If there any chance you know the syntax for it?

**Comment by nporter-adbe** [comment] 2021-02-15 02:08
Embedding a static library inside of a framework gets a bit tricky. I'm not even sure it's possible, so even if the bridging header issue was resolved you may run into another issue.

I'll need to double-check after the weekend and holiday and get back to you on Tuesday with better info.

**Comment by gpe08** [comment] 2021-02-19 15:33
To add to the situation, we are actually doing the same kind of wrapping of the adobe libraries within a framework ot ensure all apps have the same reporting system (and we are not using cocoapods either). With the static library releases, we could expose the headers and define a module map, so that the adobe SDK could be used without much trouble. 

However, since the xcframework releases that way is not possible, as the headers are no longer exposed separately to the library. There is a workaround that can be done by adding the headers manually to the swift framework, exposing them and building a modulemap. But it makes any update really complicated and prone to manual errors. (The project generated by cocoapods is actually doing this to get around it).

I believe adding the right module.modulemap to the xcframeworks will actually solve this problem and allow for easy swift integration.

**Comment by sbenedicadb** [comment] 2021-02-24 23:10
Hey @funcJeff, @gpe08 -

Please have a look at the updated XCFrameworks in the [maps branch](https://github.com/Adobe-Marketing-Cloud/acp-sdks/tree/maps/iOS).  We've manually included a `module.modulemap` for each of the distribution slices.  From our local testing, everything seems to be working nicely.  

We'd like some help from you in validating the solution in your environments.  If things look good, we'll update our deployment scripts to ensure that all future builds for manual installation include the correct modulemap files.

Thanks for your help and patience.

-steveb

**Comment by sbenedicadb** [comment] 2021-03-03 23:06
To further clarify some confusion, using an XCFramework that includes `module.modulemap` may require a couple of changes to be made in the target app:

1. Import each extension like you normally would with a Swift module - e.g. 
```    
    import ACPCore
    import ACPAnalytics
    // etc.     
```
2. If using a bridging-header, remove any code that imports `ACP*.h` header files
3. Ensure that the `User Header Search Paths` are not recursively searching the XCFrameworks

Let us know if there are any other issues popping up.  Thanks.

-steveb

**Comment by gpe08** [comment] 2021-04-23 14:19
@sbenedicadb It seems like the iOS SDK integration is working as expected so far. i need to test out some bits still, as the interface is new, but it looks promising. 

However, that's not the case for the tvOS targets. Am I correct on assuing the maps branch has only added the modulemaps for iOS so far?

**Comment by gpe08** [comment] 2021-04-23 15:52
@sbenedicadb Just finished the general integration, and it seems to be working like a charm. You should be ble to apply the changes to the main branches now 👍

**Comment by asos-chrisblackmore** [comment] 2021-05-05 16:25
+1 on allowing Adobe SDK's to be used in a framework.

Is there any appetite to include the module maps in `master`? Which version is the `maps` branch based on?

**Comment by shalehaha** [comment] 2021-05-06 15:44
@gpe08 @asos-chrisblackmore 
Thanks. And we are working on update the CI/CD to build the xcframeworks in the new format, will keep you updated.

**Comment by wshrads** [comment] 2021-05-07 03:35
Can you please provide a timeline on when this would be available in master as it is a blocker in enabling the SDK to be used in Swift based framework targets. Also, it will be helpful to mention about this in the documentation for SDK install.

**Comment by asos-chrisblackmore** [comment] 2021-05-07 08:48
@wshrads as far as I can tell, the module maps are version agnostic, so if you drop `module.modulemap` into the `Headers` folder of the `xcframework` you have (regardless of the actual version) you should be good to go. It's working for myself on the latest `ACPCore` version, and the `modulemap` files themselves are quite basic:

```
module ACPCore {
    umbrella "."
    export *
}
```

**Comment by shalehaha** [comment] 2021-05-07 15:44
@gpe08 @asos-chrisblackmore @wshrads 
We have merged the changes to the master branch.
Closing the ticket, but please let us know if you run into any problems.

**Closed by shalehaha** 2021-05-07 15:44 UTC

**Comment by wshrads** [comment] 2021-05-13 15:11
Can you let us know when do you plan for a release with this update ?
